# test.http

POST http://localhost:3000/api/check-vendor
Content-Type: application/json
Header: Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
Authorization: Bearer super-secret-jwt-token-with-at-least-32-characters-long

{
  "phone": "+919876543210"
}

###

POST http://localhost:3000/api/check-vendor
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU0MzIxL2F1dGgvdjEiLCJzdWIiOiJmNmNlZThjNC1lNDE5LTRjYWYtOWMwNS0wNWVhOWM5MzVhOWMiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ3NzMzNzg5LCJpYXQiOjE3NDc3MzAxODksImVtYWlsIjoiIiwicGhvbmUiOiI4MTA1ODg1NTUxIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoicGhvbmUiLCJwcm92aWRlcnMiOlsicGhvbmUiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6ImY2Y2VlOGM0LWU0MTktNGNhZi05YzA1LTA1ZWE5YzkzNWE5YyJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ3NzMwMTg5fV0sInNlc3Npb25faWQiOiJhZWFkY2U5NC0zMjVlLTQ1OGItYmQ4OC1mMWRhYzc4MGM1NDIiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.GhFWxhcn9SPPx6OpFWcx68wxTBYCUGoVmrnV0OopTXo

{
  "phone": "8105885551"
}

###

GET http://localhost:3000/api/catalog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU0MzIxL2F1dGgvdjEiLCJzdWIiOiJjYzE3M2M2OC0yNDcxLTQwOTYtYjljMC1mYTFmZDM4MjNkMmYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ3NzYyNDYwLCJpYXQiOjE3NDc3NTg4NjAsImVtYWlsIjoiODEwNTg4NTU1MUBnYWphay5jb20iLCJwaG9uZSI6IjgxMDU4ODU1NTEiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCIsInBob25lIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJvdHAiLCJ0aW1lc3RhbXAiOjE3NDc3NTg4NjB9XSwic2Vzc2lvbl9pZCI6IjAxNDExZjNjLTJiOGQtNGZiNi04NGI2LThmMzExOWFmOTY3ZCIsImlzX2Fub255bW91cyI6ZmFsc2V9.tBWrWqEe6Glr6jrVWvkrgN2XBRwA__HZUiFFPpR3B1Q

###

# Search test
GET http://localhost:3000/api/catalog?search=rice
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU0MzIxL2F1dGgvdjEiLCJzdWIiOiJjYzE3M2M2OC0yNDcxLTQwOTYtYjljMC1mYTFmZDM4MjNkMmYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ3NzYyNDYwLCJpYXQiOjE3NDc3NTg4NjAsImVtYWlsIjoiODEwNTg4NTU1MUBnYWphay5jb20iLCJwaG9uZSI6IjgxMDU4ODU1NTEiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCIsInBob25lIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJvdHAiLCJ0aW1lc3RhbXAiOjE3NDc3NTg4NjB9XSwic2Vzc2lvbl9pZCI6IjAxNDExZjNjLTJiOGQtNGZiNi04NGI2LThmMzExOWFmOTY3ZCIsImlzX2Fub255bW91cyI6ZmFsc2V9.tBWrWqEe6Glr6jrVWvkrgN2XBRwA__HZUiFFPpR3B1Q

###

# Pagination test
GET http://localhost:3000/api/catalog?page=2&pageSize=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU0MzIxL2F1dGgvdjEiLCJzdWIiOiJjYzE3M2M2OC0yNDcxLTQwOTYtYjljMC1mYTFmZDM4MjNkMmYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ3NzYyNDYwLCJpYXQiOjE3NDc3NTg4NjAsImVtYWlsIjoiODEwNTg4NTU1MUBnYWphay5jb20iLCJwaG9uZSI6IjgxMDU4ODU1NTEiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCIsInBob25lIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJvdHAiLCJ0aW1lc3RhbXAiOjE3NDc3NTg4NjB9XSwic2Vzc2lvbl9pZCI6IjAxNDExZjNjLTJiOGQtNGZiNi04NGI2LThmMzExOWFmOTY3ZCIsImlzX2Fub255bW91cyI6ZmFsc2V9.tBWrWqEe6Glr6jrVWvkrgN2XBRwA__HZUiFFPpR3B1Q

